- 2015-06-16-web-encoders/README.md
- 2015-06-16-web-encoders/issue-2056-samples.md
- 2015-06-16-web-encoders/issue-2056.md
This PR isn't complete yet -- it's meant to be a placeholder for the review.
> Add 2015-06-09-os-version

- 2015-09-22-misc/README.md
@vancem, @kouvel, and @jkotas: please take a look at the notes.
> 2015-09-22-misc

- 2016-02-02-ADO_NET/README.md
@saurabh500 @NickCraver @nvivo @FransBouma
> Add 2016-02-02-ADO_NET

- 2016/11-04-SpanOfT/README.md
> Fixed ref T int typo

- 2017/06-16-System.Text.Buffers/README.md
- 2017/06-16-System.Text.Buffers/System.Text.Buffers.md
@KrzysztofCwalina @ahsonkhan @shiftylogic
> Add 2017/06-16-System.Text.Buffers

- 2017/07-11-System.IO.Pipelines/README.md
- 2017/07-11-System.IO.Pipelines/System.IO.Pipelines.md
@KrzysztofCwalina @davidfowl PTAL
> Add 07-11-System.IO.Pipelines

- 2017/07-11-System.IO.Pipelines/README.md
@KrzysztofCwalina @davidfowl PTAL
> Incorporate notes from second round

- 2017/07-17-Span across CoreFx/README.md
@bartonjs @weshaggard @mellinoe @danmosemsft @stephentoub
> Add 2017-07-17-Span across CoreFx

- 2017/07-17-Span across CoreFx/README.md
Notes from our second round
@stephentoub @weshaggard @JeremyKuhne @danmosemsft
> Add 2017-07-17-Span across CoreFx (Round 2)

- 2017/08-22-Tensor/README.md
- 2017/08-22-Tensor/System.Numerics.Tensors.md
Turns out I haven't added this before
@ericstj @KrzysztofCwalina
> Add API review for Tensor<T>

- 2017/10-31-GitHub issues.md
Annotating older recording from 3 weeks ago.
> Add API review session of GitHub issues on 2017/10/31

- 2018/System.IO.Enumerations/README.md
- 2018/System.IO.Enumerations/System.IO.FileSystem.md
@JeremyKuhne please take a look to make sure I captured everything correctly.
> Add 2018/System.IO.Enumerations/

- 2018/System.IO.Enumerations2/README.md
- 2018/System.IO.Enumerations2/System.IO.Enumeration.md
> Second pass of System.IO.Enumeration

- 2018/NetCore20-vs-NetCore21-Diff/README.md
This is meant as a final pass to make sure we haven't missed anything.
> API diff between .NET Core 2.0 and .NET Core 2.1

- 2018/System.Text.Utf8Char/README.md
@GrabYourPitchforks please make sure I didn't miss anything (spoiler alert: I did because I was writing email towards the end 😈 ).
> Add notes for Utf8Char

- 2019/System.Text.Json-Serialization/README.md
Looks like I never published these. /cc @steveharter
> JSON Serializer Notes

- 2019/System.Runtime-Nullable/README.md
- 2019/System.Runtime-Nullable/System.Memory.md
- 2019/System.Runtime-Nullable/System.Threading.md
@dotnet/nullablefc @dotnet/fxdc
> Nullable Annotations for System.Memory and System.Threading.*

- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/README.md
> Add notes for nullable custom attributes

- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/README.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Collections.Concurrent.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Collections.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Diagnostics.Contracts.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Diagnostics.Debug.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Memory.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Runtime.Extensions.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Runtime.InteropServices.WindowsRuntime.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Runtime.InteropServices.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Runtime.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Threading.Thread.md
- 2019/System.Private.CoreLib-Nullable-Custom-Attributes/System.Threading.md
>  Complete notes for nullable custom attributes

- 2019/System.Text.Json-Misc/README.md
> Add notes for various JSON APIs

- 2020/01-21-command-line/README.md
> Add notes for System.CommandLine review

- 2020/05-xx-connection-abstractions/README.md
What are the next steps?
@scalablecory @davidfowl @halter73
> Networking abstractions: Add notes for round 3

- 2021/11-04-roslyn-reviews/README.md
This API was not discussed and was misslabeled. @terrajobst ptal
> Remove extraneous notes section
